version: "3"

services:
  web:
    container_name: web
    image: faris94/web:latest
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

  api:
    container_name: api
    image: faris94/api:latest  
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
