name: API
 
on:
  push:
    branches: ["main"]

  # workflow_run:
  #   workflows: ["API"]
  #   branches: [main]
  #   types:
  #     - completed

jobs:
  push_to_registry:
    runs-on: ubuntu-22.04
    steps:
     - name: copy files to target server via scp
       uses: appleboy/scp-action@v0.1.3
       with:
         host: "103.147.33.51"
         username: "root"
         port: 22
         key: "Inilah@422021"
         strip_components: 2
         source: "./docker-compose.yml"
         target: "./home/docker-compose.yml"